window.DarkestDataUrls = {
	provision: {
		Food: 'https://darkestdungeon.fandom.com/wiki/Food',
		Shovel: 'https://darkestdungeon.fandom.com/wiki/Shovel',
		Bandage: 'https://darkestdungeon.fandom.com/wiki/Bandage',
		Medicinal_Herbs: 'https://darkestdungeon.fandom.com/wiki/Medicinal_Herbs',
		Skeleton_Key: 'https://darkestdungeon.fandom.com/wiki/Skeleton_Key',
		Holy_Water: 'https://darkestdungeon.fandom.com/wiki/Holy_Water',
		Torch: 'https://darkestdungeon.fandom.com/wiki/Torch',
		Firewood: 'https://darkestdungeon.fandom.com/wiki/Firewood',
		Antivenom: 'https://darkestdungeon.fandom.com/wiki/Antivenom'
	},
	regions: {
		ruins: 'https://darkestdungeon.fandom.com/wiki/Ruins',
		warrens: 'https://darkestdungeon.fandom.com/wiki/Warrens',
		cove: 'https://darkestdungeon.fandom.com/wiki/Cove',
		weald: 'https://darkestdungeon.fandom.com/wiki/Weald',
		town: 'https://darkestdungeon.fandom.com/wiki/Village',
		'crimson-court': 'https://darkestdungeon.fandom.com/wiki/The_Crimson_Court',
		'color-of-madness': 'https://darkestdungeon.fandom.com/wiki/The_Color_of_Madness',
		darkest: 'https://darkestdungeon.fandom.com/wiki/Darkest_Dungeon'
	},
	enemies: {
		'Bone Bearer': 'https://darkestdungeon.fandom.com/wiki/Bone_Bearer',
		'Bone Arbalist': 'https://darkestdungeon.fandom.com/wiki/Bone_Arbalist',
		'Bone Courtier': 'https://darkestdungeon.fandom.com/wiki/Bone_Courtier',
		'Bone Defender': 'https://darkestdungeon.fandom.com/wiki/Bone_Defender',
		'Bone Spearman': 'https://darkestdungeon.fandom.com/wiki/Bone_Spearman',
		'Cultist Acolyte': 'https://darkestdungeon.fandom.com/wiki/Cultist_Acolyte',
		'Madman': 'https://darkestdungeon.fandom.com/wiki/Madman',
		'Swine Wretch': 'https://darkestdungeon.fandom.com/wiki/Swine_Wretch',
		'Swine Drummer': 'https://darkestdungeon.fandom.com/wiki/Swine_Drummer',
		'Large Carrion Eater': 'https://darkestdungeon.fandom.com/wiki/Large_Carrion_Eater',
		'Swine Skiver': 'https://darkestdungeon.fandom.com/wiki/Swine_Skiver',
		'Swinetaur': 'https://darkestdungeon.fandom.com/wiki/Swinetaur',
		'Bone Soldier': 'https://darkestdungeon.fandom.com/wiki/Bone_Soldier',
		'Bone Captain': 'https://darkestdungeon.fandom.com/wiki/Bone_Captain',
		'Pelagic Grouper': 'https://darkestdungeon.fandom.com/wiki/Pelagic_Grouper',
		'Pelagic Shaman': 'https://darkestdungeon.fandom.com/wiki/Pelagic_Shaman',
		'Pelagic Guardian': 'https://darkestdungeon.fandom.com/wiki/Pelagic_Guardian',
		'Drowned Thrall': 'https://darkestdungeon.fandom.com/wiki/Drowned_Thrall',
		'Uca Major': 'https://darkestdungeon.fandom.com/wiki/Uca_Major',
		'Squiffy Ghast': 'https://darkestdungeon.fandom.com/wiki/Squiffy_Ghast',
		'Swine Chopper': 'https://darkestdungeon.fandom.com/wiki/Swine_Chopper',
		'Hateful Virago': 'https://darkestdungeon.fandom.com/wiki/Hateful_Virago',
		'Necrotic Fungus': 'https://darkestdungeon.fandom.com/wiki/Necrotic_Fungus',
		'Unclean Giant': 'https://darkestdungeon.fandom.com/wiki/Unclean_Giant',
		'Fungal Artillery': 'https://darkestdungeon.fandom.com/wiki/Fungal_Artillery',
		'Fungal Scratcher': 'https://darkestdungeon.fandom.com/wiki/Fungal_Scratcher',
		'Crone': 'https://darkestdungeon.fandom.com/wiki/Crone',
		'Rabid Gnasher': 'https://darkestdungeon.fandom.com/wiki/Rabid_Gnasher',
		'Large Ectoplasm': 'https://darkestdungeon.fandom.com/wiki/Large_Ectoplasm',
		'Ectoplasm': 'https://darkestdungeon.fandom.com/wiki/Ectoplasm'
	}
};
